auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: Jeffrey's Blog”
title: Jeffrey's blog
description: Everything about Jeffrey.
url: http://alll4u.github.io
feed: /atom.xml
author_info: <a href="http://alll4u.github.io/">Jeffrey</a>
